server:
  port: 8081


wechat:
  appid: wx043980e60c301947
  appsecret: cd08fc1919f82475471a2828d7bf7ee2
aliyun:
  accessKeyId: "LTAI5tGcQrNhSDtCCHUMVPRM"
  accessKeySecret: C1X4X9e8dkIc8pUTEzRcMBpaARko2U
spring:
#  profiles:
#    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/sunset_test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: sunset_test
    password: dsdNnZDyXEabhaaW
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB # 图片上传的大小
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunset.entity
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
springdoc:
  swagger-ui:
    path: /api
    enabled: true # 开启swagger
  api-docs:
    path: /v1
    enabled: true
  packages-to-scan: com.sunset.controller
logging:
  file:
    name: running.log

