spring:
  datasource:
    url: jdbc:mysql://101.126.150.83:3306/sunset_test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: sunset_test
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver